---
title: "Meta-Analysis"
author: "Xinyang Zhang"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load libraries and read study data:

```{r message=FALSE, warning=FALSE}
library(dplyr)
library(meta)
setwd("/Users/xinyang/Library/CloudStorage/Box-Box/Cancer_Mircrobiome/Cancer-Microbiome")

df <- read.csv('data/forestplotData.csv')
```

# Perform meta-analysis using `metagen`

Based on https://link.springer.com/chapter/10.1007/978-3-319-21416-0_2

```{r fig.height=6, fig.width=10}

# Creating a forest plot
mg1 <- metagen(coef, stderr,
               studlab=batch, data = df,
               sm="coef", common = TRUE, random = TRUE)
print(mg1)
pdf(file='forestplot_BGC0001817.pdf', height = 6, width = 10)
forest(mg1, sortvar = Year, layout="RevMan5",
       text.common = 'Total (fixed effect, 95% CI)', text.w.common = 'fixed',
       label.left = "favors treatment", label.right = "favors control",
       print.tau2 = FALSE)
dev.off()
```

```{r}
# Creating a forest plot
df1 <- read.csv('data/forestplot_BGC0000800.csv')
mg2 <- metagen(coef, stderr,
               studlab=batch, data = df1,
               sm="coef", common = TRUE, random = TRUE)
print(mg2)
pdf(file='forestplot_BGC0000800.pdf', height = 6, width = 10)
forest(mg2, sortvar = Year, layout="RevMan5",
       text.common = 'Total (fixed effect, 95% CI)', text.w.common = 'fixed',
       label.left = "favors treatment", label.right = "favors control",
       print.tau2 = FALSE)
dev.off()
```
```{r}
# Creating a forest plot
df3 <- read.csv('data/forestplot_BGC0001322.csv')
mg3 <- metagen(coef, stderr,
               studlab=batch, data = df3,
               sm="coef", common = TRUE, random = TRUE)
print(mg3)
pdf(file='forestplot_BGC0001322.pdf', height = 6, width = 10)
forest(mg3, sortvar = Year, layout="RevMan5",
       text.common = 'Total (fixed effect, 95% CI)', text.w.common = 'fixed',
       label.left = "favors treatment", label.right = "favors control",
       print.tau2 = FALSE)
dev.off()
```
```{r}
# Creating a forest plot
df4 <- read.csv('data/forestplot_BGC0000437.csv')
mg4 <- metagen(coef, stderr,
               studlab=batch, data = df4,
               sm="coef", common = TRUE, random = TRUE)
print(mg4)
pdf(file='forestplot_BGC0000437.pdf', height = 6, width = 10)
forest(mg4, sortvar = Year, layout="RevMan5",
       text.common = 'Total (fixed effect, 95% CI)', text.w.common = 'fixed',
       label.left = "favors treatment", label.right = "favors control",
       print.tau2 = FALSE)
dev.off()
```

# Subgroup analyses: